# Generated by Django 6.1.1 on 2026-10-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_movie_video_alter_movie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='movies/')),
                ('video', models.FileField(blank=True, upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Phase2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='movies/')),
                ('video', models.FileField(blank=True, upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Phase3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='movies/')),
                ('video', models.FileField(blank=True, upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Phase4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='movies/')),
                ('video', models.FileField(blank=True, upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Phase5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='movies/')),
                ('video', models.FileField(blank=True, upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Phase6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='movies/')),
                ('video', models.FileField(blank=True, upload_to='videos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
